name: '[PRT] Quality Engineering'

on:
  pull_request_target:
    branches:
      - main
      - master
    types:
      - labeled

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@main
    with:
      nodeLint: true
      nodeTest: false
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_wish-list-ts
      nodeSonarOrganization: vtex-apps
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_wish-list-dotnet
      dotnetSonarOrganization: vtex-apps
      cypress: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
