name: '[PRN] Quality Engineering'

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@v1.0.0
    with:
      danger: true
      dangerRequireChangelog: false
      nodeLint: true
      reactTest: false
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_wish-list-ts
      nodeSonarOrganization: vtex-apps
      dotnetLint: true
      dotnetSonar: true
      dotnetSonarProjectKey: vtex-apps_wish-list-dotnet
      dotnetSonarOrganization: vtex-apps
      cypress: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      cypressJson: ${{ secrets.VTEX_QE }}
